FUNCTION(BMC_TARGET_PRE TARGET)
    set(OUTPUT_NAME ${TARGET})
    ADD_EXECUTABLE(${TARGET})

    STRING(TOUPPER ${BOARD} BOARD_UPPER)
    target_compile_definitions(${TARGET} PRIVATE
        BOARD_${BOARD_UPPER}
    )
    set(CONFIG_INC_DIRS
        ${MY_SRC_DIR}/config
    )

    # FIXME: remove it
    target_include_directories(${TARGET} PRIVATE
        ${CONFIG_INC_DIRS}
    )

    TARGET_INCLUDE_DIRECTORIES(STM32HAL PRIVATE
        ${CONFIG_INC_DIRS}
        ${MY_LIB_DIR}/common
    )
    TARGET_INCLUDE_DIRECTORIES(FreeRTOS PRIVATE
        ${CONFIG_INC_DIRS}
    )
ENDFUNCTION()

FUNCTION(BMC_TARGET_POST TARGET)
    TARGET_LINK_LIBRARIES(${TARGET}
        FreeRTOS
        CMSIS
        STM32HAL
    )
    STM32_SET_TARGET_PROPERTIES(${TARGET})
    STM32_ADD_HEX_BIN_TARGETS(${TARGET})
    STM32_ADD_DUMP_TARGET(${TARGET})
    STM32_PRINT_SIZE_OF_TARGETS(${TARGET})
    add_custom_command(TARGET ${TARGET} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:${TARGET}> ${CMAKE_PROJECT_NAME}-${GIT_DESCR}.elf
    )
ENDFUNCTION()
